name: "Bunny.net Storage Deployer"
author: "Kinane"
description: "A github action to deploy a glob pattern to bunny.net storage and flush the associated pull zone"
inputs:
  upload:
    description: >
      It will upload files and folders if "true" provided. source, storageZoneName and storagePassword inputs should be provided.
    type: boolean
    default: false
  remove:
    description: >
      It will remove all the files from storage before uploading if "true" provided.
    type: boolean
    default: false
  storageName:
    description: >
      The name of storage zone where you are connecting to.
    required: true
  storageEndpoint:
    description: >
      The storage endpoint. Default value is storage.bunnycdn.com
    default: storage.bunnycdn.com
  storagePassword:
    description: >
      The storage password. It should be read and write capable.
    required: true
  sourcePattern:
    description: >
      The glob pattern to retrieve the files from, like `./dist/**/*.js`
    required: true
  destination:
    description: >
      The destination directory that should be uploaded to in the bunny storage zone. (Example: www). The destination should not have a trailing / as in www/.

      If you want to upload files to a nested directory, you can specify the path to the directory in the destination parameter. For example, if you want to upload files to a directory called assets inside the www directory, you can set the destination parameter to www/assets.

      Note that the nested directory will be automatically created by the CDN if it does not already exist.
    required: true
  purgePullZone:
    description: >
      It will purge the pull zone if "true" provided. pullZoneId and accessKey inputs should be provided.
    type: boolean
    default: false
  apiKey:
    description: >
      You can retrieve your api key from your profile settings
    required: true
  pullZoneId:
    description: > 
      You can retrieve your pull zone id directly from its url: https://dash.bunny.net/cdn/PULL_ZONE_ID/general/hostnames
    required: true
  verbose:
    description: >
      Verbose mode
    required: false
    default: false

runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "upload-cloud"
  color: "orange"